version: "1.0"
info:
  model: int-scaffold
packages:
- name: Test1905Project
  gitServerName: lakshitha
  gitUrl: https://github.com/Lakshitha-Ramesh-IBM
  gitUsername: Lakshitha-Ramesh-IBM
  gitBranch: main
